// <auto-generated />
using System;
using Animatch.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animatch.Infrastructure.Migrations
{
    [DbContext(typeof(AnimatchDbContext))]
    [Migration("20260617161921_changeuserprofile")]
    partial class changeuserprofile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogCompatibility", b =>
                {
                    b.Property<Guid>("DogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompatibilityId")
                        .HasColumnType("int");

                    b.HasKey("DogId", "CompatibilityId");

                    b.HasIndex("CompatibilityId");

                    b.ToTable("DogCompatibilities");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogMedia", b =>
                {
                    b.Property<Guid>("DogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("DogId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("DogMedias");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogMedicalHistory", b =>
                {
                    b.Property<Guid>("DogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MedicalHistoryId")
                        .HasColumnType("int");

                    b.HasKey("DogId", "MedicalHistoryId");

                    b.HasIndex("MedicalHistoryId");

                    b.ToTable("DogMedicalHistories");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogPersonality", b =>
                {
                    b.Property<Guid>("DogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PersonalityId")
                        .HasColumnType("int");

                    b.HasKey("DogId", "PersonalityId");

                    b.HasIndex("PersonalityId");

                    b.ToTable("DogPersonalities");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogSpecialNeeds", b =>
                {
                    b.Property<Guid>("DogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpecialNeedsId")
                        .HasColumnType("int");

                    b.HasKey("DogId", "SpecialNeedsId");

                    b.HasIndex("SpecialNeedsId");

                    b.ToTable("DogSpecialNeeds");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserCompatibility", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompatibilityId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CompatibilityId");

                    b.HasIndex("CompatibilityId");

                    b.ToTable("UserCompatibilities");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogAge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DogAgeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DogAgeId");

                    b.HasIndex("DogAgeId");

                    b.ToTable("UserDogAges");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogEnergy", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EnergyLevelId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EnergyLevelId");

                    b.HasIndex("EnergyLevelId");

                    b.ToTable("UserDogEnergies");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogGender", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DogGenderId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DogGenderId");

                    b.HasIndex("DogGenderId");

                    b.ToTable("UserDogGenders");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogSize", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DogSizeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DogSizeId");

                    b.HasIndex("DogSizeId");

                    b.ToTable("UserDogSizes");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserPersonality", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PersonalityId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PersonalityId");

                    b.HasIndex("PersonalityId");

                    b.ToTable("UserPersonalities");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserRace", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("UserDogRaces");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Compatibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Compatibilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Good with kids"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Good with animals"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Good with strangers"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EnergyLevelEnum")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Race")
                        .HasColumnType("int");

                    b.Property<Guid>("ShelterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.DogAge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DogAges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Puppy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Young"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adult"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Senior"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.DogGenderPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DogGenders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.DogRacePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pure breed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mixed breed"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.DogSizePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DogSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Large"
                        },
                        new
                        {
                            Id = 4,
                            Name = "XLarge"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.EnergyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DogEnergyLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AdopterLikedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ConversationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ShelterResponseAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("UserId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MedicalHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allergies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vaccinated"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Microchipped"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sterilized"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Medical problems"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShelterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("ShelterId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Personality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Personalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Playful"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sensitive"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Protective"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Affectionate"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Independent"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Smart"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sociable"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dominant"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Shelter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreationYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ShelterStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Shelters");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.SpecialNeeds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SpecialNeeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anxiety"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Afraid of men"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Afraid of noises"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AccountCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccountCompleted = true,
                            AccountType = 1,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@animatch.be",
                            FirstName = "Super",
                            Gender = 2,
                            LastName = "Admin",
                            Password = "wNPUpqDi7HH1EjwwPggiRrnUlZUlJlwBUu25Sh9rqvJsfKkMN5lFa5/bcHE2yrqw"
                        });
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxDistance")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDistances");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdoptionPermit")
                        .HasColumnType("bit");

                    b.Property<bool>("AlreadyAdopted")
                        .HasColumnType("bit");

                    b.Property<int>("AnimalType")
                        .HasColumnType("int");

                    b.Property<int>("AnimalsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasAnimals")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserExperiences");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserFamilyCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("bit");

                    b.Property<int>("HousingType")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFamilyConditions");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserLifestyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActiveLifestyle")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DogAloneHours")
                        .HasColumnType("int");

                    b.Property<bool>("FinanciallyStable")
                        .HasColumnType("bit");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<bool>("RemoteWork")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLifestyles");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogCompatibility", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Compatibility", "Compatibility")
                        .WithMany()
                        .HasForeignKey("CompatibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.Dog", "Dog")
                        .WithMany("DogCompatibilities")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compatibility");

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogMedia", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Dog", "Dog")
                        .WithMany("DogMedias")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogMedicalHistory", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Dog", "Dog")
                        .WithMany("DogMedicalHistories")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.MedicalHistory", "MedicalHistory")
                        .WithMany()
                        .HasForeignKey("MedicalHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogPersonality", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Dog", "Dog")
                        .WithMany("DogPersonalities")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.Personality", "Personality")
                        .WithMany()
                        .HasForeignKey("PersonalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Personality");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.DogSpecialNeeds", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Dog", "Dog")
                        .WithMany("DogSpecialNeeds")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.SpecialNeeds", "SpecialNeeds")
                        .WithMany()
                        .HasForeignKey("SpecialNeedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("SpecialNeeds");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserCompatibility", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Compatibility", "Compatibility")
                        .WithMany()
                        .HasForeignKey("CompatibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compatibility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogAge", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.DogAge", "DogAge")
                        .WithMany()
                        .HasForeignKey("DogAgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DogAge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogEnergy", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.EnergyLevel", "EnergyLevel")
                        .WithMany()
                        .HasForeignKey("EnergyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergyLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogGender", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.DogGenderPreference", "DogGender")
                        .WithMany()
                        .HasForeignKey("DogGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DogGender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserDogSize", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.DogSizePreference", "DogSize")
                        .WithMany()
                        .HasForeignKey("DogSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DogSize");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserPersonality", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Personality", "Personality")
                        .WithMany()
                        .HasForeignKey("PersonalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.ConnectingTables.UserRace", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.DogRacePreference", "DogRace")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DogRace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Admin", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Dog", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Shelter", "Shelter")
                        .WithMany()
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Match", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Message", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.Shelter", "Shelter")
                        .WithMany()
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Shelter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserDistance", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserExperience", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserFamilyCondition", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.UserLifestyle", b =>
                {
                    b.HasOne("Animatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Animatch.Domain.Entities.Dog", b =>
                {
                    b.Navigation("DogCompatibilities");

                    b.Navigation("DogMedias");

                    b.Navigation("DogMedicalHistories");

                    b.Navigation("DogPersonalities");

                    b.Navigation("DogSpecialNeeds");
                });
#pragma warning restore 612, 618
        }
    }
}
