name: CICD Animatch Back

on:
  push:
    branches: [main, develop, "feature/**", "features/**"]
    paths:
      - "Animatch/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "Animatch/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore dependencies
        run: dotnet restore Animatch.slnx
      - name: Build solution
        run: dotnet build Animatch.slnx --configuration Release --no-restore